
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.estructuraGramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ASIGNACION_INF = 7;
  public static final int SALTO_DE_LINEA = 20;
  public static final int ASIGNACION_ER = 9;
  public static final int ENTERO = 26;
  public static final int O = 14;
  public static final int PR_REAL = 34;
  public static final int SEPARADOR = 10;
  public static final int PR_AUTOR = 3;
  public static final int PR_CADENA = 35;
  public static final int IGNORAR = 23;
  public static final int PR_TERMINAL = 31;
  public static final int PR_VERSION = 4;
  public static final int VERSION = 27;
  public static final int TABULACION = 21;
  public static final int PR_EXTENSION = 6;
  public static final int ID = 28;
  public static final int RETORNO = 22;
  public static final int PR_NO = 32;
  public static final int RANGO_LETRAS_MIN = 30;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int RANGO_NUMEROS = 29;
  public static final int CADENA = 24;
  public static final int PAR_C = 18;
  public static final int PAR_A = 17;
  public static final int UNA_O_MAS_VECES = 11;
  public static final int FIN_DE_LINEA = 19;
  public static final int JAVA_CODE = 25;
  public static final int PUEDE_O_NO_PUEDE = 13;
  public static final int PR_NOMBRE = 2;
  public static final int COR_C = 16;
  public static final int PR_ENTERO = 33;
  public static final int COR_A = 15;
  public static final int CERO_O_MAS_VECES = 12;
  public static final int PR_LANZAMIENTO = 5;
  public static final int ASIGNACION_GRAMA = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_NOMBRE",
  "PR_AUTOR",
  "PR_VERSION",
  "PR_LANZAMIENTO",
  "PR_EXTENSION",
  "ASIGNACION_INF",
  "ASIGNACION_GRAMA",
  "ASIGNACION_ER",
  "SEPARADOR",
  "UNA_O_MAS_VECES",
  "CERO_O_MAS_VECES",
  "PUEDE_O_NO_PUEDE",
  "O",
  "COR_A",
  "COR_C",
  "PAR_A",
  "PAR_C",
  "FIN_DE_LINEA",
  "SALTO_DE_LINEA",
  "TABULACION",
  "RETORNO",
  "IGNORAR",
  "CADENA",
  "JAVA_CODE",
  "ENTERO",
  "VERSION",
  "ID",
  "RANGO_NUMEROS",
  "RANGO_LETRAS_MIN",
  "PR_TERMINAL",
  "PR_NO",
  "PR_ENTERO",
  "PR_REAL",
  "PR_CADENA",
  "COMA"
  };
}

