
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.estructuraGramatica.secciones;

import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserSecciones extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserSecciones() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserSecciones(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserSecciones(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\005\000\002\002" +
    "\005\000\002\003\005\000\002\003\004\000\002\004\005" +
    "\000\002\004\005\000\002\005\005\000\002\005\005\000" +
    "\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\033\000\006\003\005\004\004\001\002\000\004\005" +
    "\034\001\002\000\004\005\010\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\006\004\012\005" +
    "\013\001\002\000\004\002\uffff\001\002\000\004\005\032" +
    "\001\002\000\006\003\015\004\014\001\002\000\004\005" +
    "\030\001\002\000\004\005\017\001\002\000\004\002\ufffd" +
    "\001\002\000\006\003\021\004\020\001\002\000\004\005" +
    "\026\001\002\000\004\005\023\001\002\000\004\002\ufffb" +
    "\001\002\000\004\004\024\001\002\000\004\002\ufff8\001" +
    "\002\000\004\002\ufff9\001\002\000\004\004\024\001\002" +
    "\000\004\002\ufffa\001\002\000\006\003\021\004\020\001" +
    "\002\000\004\002\ufffc\001\002\000\006\003\015\004\014" +
    "\001\002\000\004\002\ufffe\001\002\000\006\004\012\005" +
    "\013\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\033\000\004\002\005\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\003\010\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\015\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\024" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\006" +
    "\026\001\001\000\002\001\001\000\004\005\030\001\001" +
    "\000\002\001\001\000\004\004\032\001\001\000\002\001" +
    "\001\000\004\003\034\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserSecciones$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserSecciones$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserSecciones$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public ParserSecciones(LexerSecciones lex) { 
        super(lex);   
    }

    public void unrecovered_syntax_error(Symbol cur_token){
        System.err.println("No se pudo recuperar y seguir analizando "+cur_token.value);
    }

    public void syntax_error(Symbol s){
        String message = "";
        StringBuilder m = new StringBuilder("Error:");
        String cadena = (String) s.value;
        int linea = s.left;
        int columna = s.right;
        switch(s.toString()){
            
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserSecciones$actions {


  private final ParserSecciones parser;

  /** Constructor */
  CUP$ParserSecciones$actions(ParserSecciones parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserSecciones$do_action_part00000000(
    int                        CUP$ParserSecciones$act_num,
    java_cup.runtime.lr_parser CUP$ParserSecciones$parser,
    java.util.Stack            CUP$ParserSecciones$stack,
    int                        CUP$ParserSecciones$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserSecciones$result;

      /* select the action based on the action number */
      switch (CUP$ParserSecciones$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-1)).right;
		List<String> start_val = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-1)).value;
		RESULT = start_val;
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserSecciones$parser.done_parsing();
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= SECCION SEPARADOR resto1 
            {
              List<String> RESULT =null;
		int informacionleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).left;
		int informacionright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).right;
		String informacion = (String)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).value;
		int seccionesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int seccionesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		List<String> secciones = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        if(secciones == null){
                            secciones = new ArrayList<String>();
                            if(informacion != null) secciones.add(informacion);
                        }else{
                            secciones.add(0, informacion);
                        }
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // S ::= error SEPARADOR resto1 
            {
              List<String> RESULT =null;
		int seccionesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int seccionesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		List<String> secciones = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        if(secciones == null) secciones = new ArrayList<String>();
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // resto1 ::= SECCION SEPARADOR resto2 
            {
              List<String> RESULT =null;
		int codigoUsuarioleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).left;
		int codigoUsuarioright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).right;
		String codigoUsuario = (String)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).value;
		int seccionesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int seccionesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		List<String> secciones = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        if(secciones == null){
                            secciones = new ArrayList<String>();
                            if(codigoUsuario != null) secciones.add(codigoUsuario);
                        }else{
                            secciones.add(0, codigoUsuario);
                        }
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("resto1",1, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // resto1 ::= SEPARADOR resto2 
            {
              List<String> RESULT =null;
		int seccionesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int seccionesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		List<String> secciones = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        if(secciones == null) secciones = new ArrayList<String>();
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("resto1",1, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // resto2 ::= SECCION SEPARADOR resto3 
            {
              List<String> RESULT =null;
		int expresionesRegularesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).left;
		int expresionesRegularesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).right;
		String expresionesRegulares = (String)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).value;
		int seccionesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int seccionesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		List<String> secciones = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        if(secciones == null){
                            secciones = new ArrayList<String>();
                            if(expresionesRegulares != null) secciones.add(expresionesRegulares);
                        }else{
                            secciones.add(0, expresionesRegulares);
                        }
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("resto2",2, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // resto2 ::= error SEPARADOR resto3 
            {
              List<String> RESULT =null;
		int seccionesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int seccionesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		List<String> secciones = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        if(secciones == null) secciones = new ArrayList<String>();
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("resto2",2, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // resto3 ::= SECCION SEPARADOR resto4 
            {
              List<String> RESULT =null;
		int simbolosleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).left;
		int simbolosright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).right;
		String simbolos = (String)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)).value;
		int seccionesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int seccionesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		List<String> secciones = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        if(secciones == null){
                            secciones = new ArrayList<String>();
                            if(simbolos != null) secciones.add(simbolos);
                        }else{
                            secciones.add(0, simbolos);
                        }
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("resto3",3, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // resto3 ::= error SEPARADOR resto4 
            {
              List<String> RESULT =null;
		int seccionesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int seccionesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		List<String> secciones = (List<String>)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        if(secciones == null) secciones = new ArrayList<String>();
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("resto3",3, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.elementAt(CUP$ParserSecciones$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // resto4 ::= SECCION 
            {
              List<String> RESULT =null;
		int reglasGramaticalesleft = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).left;
		int reglasGramaticalesright = ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()).right;
		String reglasGramaticales = (String)((java_cup.runtime.Symbol) CUP$ParserSecciones$stack.peek()).value;
		
                        List<String> secciones = new ArrayList<String>();
                        secciones.add(reglasGramaticales);
                        RESULT = secciones;
                    
              CUP$ParserSecciones$result = parser.getSymbolFactory().newSymbol("resto4",4, ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSecciones$stack.peek()), RESULT);
            }
          return CUP$ParserSecciones$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserSecciones$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserSecciones$do_action(
    int                        CUP$ParserSecciones$act_num,
    java_cup.runtime.lr_parser CUP$ParserSecciones$parser,
    java.util.Stack            CUP$ParserSecciones$stack,
    int                        CUP$ParserSecciones$top)
    throws java.lang.Exception
    {
              return CUP$ParserSecciones$do_action_part00000000(
                               CUP$ParserSecciones$act_num,
                               CUP$ParserSecciones$parser,
                               CUP$ParserSecciones$stack,
                               CUP$ParserSecciones$top);
    }
}

}
